Improve invitation list
Gewaer/gw-settings pull request #37
Opened 2020-07-24 06:40 UTC by jesusantguerrero

Fix delete invites

Add resend invite

Add copy invitehash

2020-07-24 06:41 UTC, jesusantguerrero commented
Note: Ask for resend invite endpoint

2020-07-29 15:49 UTC, SparoHawk reviewed
Two comments more than anything:
1. We could use a copy package to avoid having compatibility issues. What do you think?
2. I do not know why we need to have a copy invite link. Personally I think it should always be that you re-send the invitation email. Copying the link could promote having users with incorrect emails in the system.

2020-07-30 15:23 UTC, jesusantguerrero commented
1- Under the hood, the libraries use the same pattern I used and as this was the only case I didn't want to add a library just for this case. But if we had/will have other use cases when this method is not enough we should go with a library.

2- The use case that max said if we want to send the link through chat for faster but I agree, re-send the invitation is more secure. I will talk to him.

2020-07-30 15:35 UTC, jesusantguerrero commented
Update: we are going to use just the resend here and delete the copy functionality

2020-07-30 15:59 UTC, SparoHawk commented
1.- Understandable. Let's do that then.
2.- Awesome. Let me know when the changes are pushed.

2020-07-30 16:27 UTC, jesusantguerrero commented
Done

2020-07-30 16:40 UTC, SparoHawk requested changes

2020-07-30 16:40 UTC, SparoHawk commented on src/components/companies/users/list.vue
> +
```suggestion
```

2020-07-30 16:40 UTC, SparoHawk commented on src/components/companies/users/list.vue
> +                    text: "The invite has been sent",
```suggestion
                    text: "A new invitation link has been sent to the user.",
```

2020-07-30 17:46 UTC, SparoHawk approved these changes

2020-07-30 17:46 UTC, merged